# Ejercicio 1: Crear un array

In [1]:
#Importar la biblioteca numpy
import numpy as np

In [5]:
# Crea un array de 1D con valores del 0 al 9
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Crea un array 2D de forma (3, 3) con valores del 0 al 8
arr2 = np.arange(9).reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Ejercicio 2: Operaciones básicas

In [9]:
# Suma, resta, multiplicación y división de dos arrays

arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])


In [10]:
print("Suma")
suma = arr3 + arr4 
print(suma)

Suma
[5 7 9]


In [14]:
print("Resta")
resta = arr3 - arr4
print(resta)

Resta
[-3 -3 -3]


In [15]:
print("Multiplicacion")
multiplicacion = arr3 * arr4 
print(multiplicacion)

Multiplicacion
[ 4 10 18]


In [16]:
print("Division")
division = arr3 / arr4
print(division)

Division
[0.25 0.4  0.5 ]


# Ejercicio 3: Funciones estadísticas

In [17]:
# Calcular la media, mediana y desviación estándar de un array

arr5 = np.array([2,4,6,8,10])

In [18]:
print("Media: ",np.mean(arr5))
print("Mediana",np.median(arr5))
print("Desviacion Estandar",np.std(arr5))

Media:  6.0
Mediana 6.0
Desviacion Estandar 2.8284271247461903


# Ejercicio 4: Indexación y selección

In [22]:
# Seleccionar elementos específicos de un array
arr6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
print("Segunda Columna") #[fila_inicio:fila_fin, columna]
print(arr6[0:,1])

Segunda Columna
[2 5 8]


In [28]:
# Seleccionar la diagonal
print("Diagonal")
print(np.diagonal(arr6))

Diagonal
[1 5 9]
