# Creación de Arrays

In [2]:
#Crear un array a partir de una lista
import numpy as np

lista = [1, 2, 3, 4, 5]

array_creado = np.array(lista)

print(array_creado)


[1 2 3 4 5]


In [4]:
#Crear un array de ceros de tamaño 5x5

array_ceros = np.zeros((5,5))

print(array_ceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
#Crear un array de unos de tamaño 3x3
array_one = np.ones((3,3))
print(array_one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#Crear un array con valores espaciados uniformemente de 0 a 9
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#Crear un array con 6 valores espaciados linealmente entre 0 y 1
array_espaciado = np.linspace(0,1,6)
print(array_espaciado)

[0.  0.2 0.4 0.6 0.8 1. ]


# Operaciones Básicas

In [11]:
#Realizar una suma, resta, multiplicación y división entre dos arrays

array_1 = np.array([5,4,2])
array_2 = np.array([6,4,9])
suma = np.add(array_1, array_2)
resta = np.subtract(array_1, array_2)
multiplicacion = np.multiply(array_1, array_2)
division = np.divide(array_1, array_2)

print("La suma es: ",suma)
print("La resta es: ",resta)
print("La multiplicacion es: ",multiplicacion)
print("La division es: ",division)

La suma es:  [11  8 11]
La resta es:  [-1  0 -7]
La multiplicacion es:  [30 16 18]
La division es:  [0.83333333 1.         0.22222222]


In [12]:
#Calcular el producto punto de dos arrays
producto_punto = np.dot(array_1,array_2)
print(producto_punto)

64


In [13]:
#Transponer un array
trasponer = np.transpose(array_1)
print(trasponer)

[5 4 2]


# Operaciones Estadísticas

In [16]:
#Calcular la media, suma, valor mínimo y valor máximo de un array

array_aleatorio = np.random.randint(1,100,size = 10)

media = np.mean(array_aleatorio)
suma = np.sum(array_aleatorio)
minimo = np.min(array_aleatorio)
maximo = np.max(array_aleatorio)

print(array_aleatorio)
print(media)
print()
print(suma)
print()
print(minimo)
print()
print(maximo)


[46 37 55 27 63 55 62 97 63 39]
54.4

544

27

97


In [21]:
#Cambiar la forma de un array
array_2 = np.random.randint(1,20,size = (2,3))
print(array_2)

print()
cambiar_forma = np.reshape(array_2,(3,2))

print(cambiar_forma)

[[11 18 12]
 [13 13 18]]

[[11 18]
 [12 13]
 [13 18]]


# Álgebra Lineal

In [26]:
#Calcular el determinante de una matriz 2x2
nuevo_array = np.array([[1,2],[2,5]])
print(nuevo_array)

print()

determinante = np.linalg.det(nuevo_array)

print(determinante)

[[1 2]
 [2 5]]

1.0


In [30]:
#Calcular la matriz inversa de una matriz 3x3

matriz_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz_3x3)
inversa = np.linalg.inv(matriz_3x3)
print()
print(inversa)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [31]:
#Calcular los valores propios y vectores propios de una matriz 4x4
matriz_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

autovalores_autovectores = np.linalg.eig(matriz_4x4)

print(matriz_4x4)

print()

print(autovalores_autovectores)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

(array([ 3.62093727e+01, -2.20937271e+00,  2.80575969e-16, -8.29646454e-16]), array([[-0.15115432, -0.72704996, -0.01128698, -0.250341  ],
       [-0.34923733, -0.28320876,  0.42321091,  0.69689908],
       [-0.54732033,  0.16063243, -0.81256087, -0.64277516],
       [-0.74540333,  0.60447363,  0.40063694,  0.19621708]]))


# Funciones Universales

In [34]:
#Calcular el seno, coseno, exponencial y logaritmo natural de un array

array_angulos = np.array([0, np.pi/2, np.pi])

seno = np.sin(array_angulos)

coseno = np.cos(array_angulos)

exponencial = np.exp(array_angulos)

logaritmo = np.log(array_angulos)

print(seno)

print()

print(coseno)

print()

print(exponencial)

print()

print(logaritmo)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]

[ 1.000000e+00  6.123234e-17 -1.000000e+00]

[ 1.          4.81047738 23.14069263]

[      -inf 0.45158271 1.14472989]


C:\Users\braia\AppData\Local\Temp\ipykernel_12196\3932995182.py:11: RuntimeWarning: divide by zero encountered in log
  logaritmo = np.log(array_angulos)


In [35]:
#Realizar indexación y slicing en un array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

elemento = array_2d[1,2]

subarray = array_2d[:2,1:]

print(elemento)

print()

print(subarray)

6

[[2 3]
 [5 6]]


# Generación de Números Aleatorios

In [37]:
#Generar un array de 10 números enteros aleatorios entre 1 y 100

array_aleatorio = np.random.randint(1,101,size = 10)

print(array_aleatorio)

[80 47 22 74 70 33 43 36 62 87]


In [38]:
#Generar una matriz 2x3 con números aleatorios uniformemente distribuidos entre 0 y 1

matriz_uniforme = np.random.rand(2,3)

print(matriz_uniforme)

[[0.21939078 0.33592823 0.37228672]
 [0.70241376 0.28918966 0.80706414]]


In [41]:
#Generar un array de 5 números aleatorios con distribución normal (media 0, desviación estándar 1)

array_normal = np.random.randn(5)

print(array_normal)


[ 2.94572     0.44287336 -0.54586137  1.41222227 -0.29924358]
