# Ejercicio 1: Manipulación de arrays

In [4]:
import numpy as np

In [5]:
# Crea un array de 1D con números aleatorios entre 1 y 50
array_1 = np.random.randint(1,51,size = 8)

In [6]:
# Imprime el array original
print("Array Original")
print(array_1)

Array Original
[ 4 29 22 15  5  4 44 18]


In [7]:
# Invierte el orden de los elementos en el array
array_1_invertido = np.flip(array_1)

In [8]:
print("Array Invertido")
print(array_1_invertido)

Array Invertido
[18 44  4  5 15 22 29  4]


In [9]:
# Cambia el shape del array a una matriz 2x4
matriz2_x_4 = array_1.reshape(2,4)

In [11]:
#Matriz 2 x 4
print("Matriz 2 x 4")
print(matriz2_x_4)

Matriz 2 x 4
[[ 4 29 22 15]
 [ 5  4 44 18]]


# Ejercicio 2: Operaciones con matrices

In [12]:
# Crea dos matrices 2x3 con valores aleatorios entre 1 y 10

array_1 = np.random.randint(1,11,size = (2,3))
array_2 = np.random.randint(1,11,size = (2,3))

In [13]:
# Imprime las matrices originales
print("Matriz A")
print(array_1)

[[10 10  2]
 [10  5  5]]


In [15]:
print("Matriz B")
print(array_2)

Matriz B
[[ 7  3  1]
 [ 8 10  7]]


In [16]:
# Realiza la multiplicación elemento a elemento de las dos matrices
multiplicacion_elemento_a_elemento = np.multiply(array_1,array_2)

In [17]:
print("\nMultiplicación elemento a elemento:")
print(multiplicacion_elemento_a_elemento)


Multiplicación elemento a elemento:
[[70 30  2]
 [80 50 35]]


In [18]:
# Calcula la suma de todas las entradas de la matriz resultante

suma_matriz = np.sum(multiplicacion_elemento_a_elemento)

In [19]:
print("\nSuma total:")
print(suma_matriz)


Suma total:
267


# Ejercicio 3: Filtrado y Slicing

In [20]:
# Crea un array 2D de forma (4, 6) con valores aleatorios entre 1 y 100
array_1 = np.random.randint(1,101,size = (4,6))

In [21]:
# Imprime el array original
print("Array Original")
print(array_1)

Array Original
[[87 73 81 51 98 54]
 [16 34 65 50 10 79]
 [40 32 96 98 42  8]
 [18 44 37 41  3 33]]


In [22]:
# Selecciona la submatriz formada por las primeras 2 filas y las primeras 3 columnas
submatriz = array_1[:2,:3]

In [23]:
print("Submatriz")
print(submatriz)

Submatriz
[[87 73 81]
 [16 34 65]]


In [24]:
# Filtra los valores mayores a 50 en la submatriz

filtracion = submatriz[submatriz > 50]

In [25]:
print("\nValores mayores a 50:")
print(filtracion)


Valores mayores a 50:
[87 73 81 65]


# Ejercicio 4: Crear un array con condiciones

In [26]:
# Crea un array de 1D con números aleatorios entre -10 y 10
array = np.random.randint(-10,11,size = 10)

In [27]:
# Imprime el array original
print("Array Original")
print(array)

Array Original
[  2   6   8   0   2   5  10 -10   3   7]


In [28]:
# Crea un nuevo array con solo los valores positivos del array original
valores_positivos = array[array > 0]

In [30]:
print("\nArray de valores positivos:")
print(valores_positivos)


Array de valores positivos:
[ 2  6  8  2  5 10  3  7]
